build:
    environment:
        postgresql: false
        redis: false
    nodes:
        analysis:
            project_setup:
                override: true
            tests:
                override: [php-scrutinizer-run]
        php71:
            environment:
                php: 7.1
    tests:
        override:
            -
                command: 'composer run scrutinizer --timeout=0'
                idle_timeout: 600
                coverage:
                    file: 'phpunit.clover'
                    format: 'clover'

checks:
    php:
        code_rating: true
        duplication: false

filter:
    excluded_paths:
        - './Tests/'
